# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import re
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def __init__(self):
        self.math_operations = ['+', '-', '*', '/']

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 500, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(32)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_result.setObjectName("label_result")
        self.button_num_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_1.setGeometry(QtCore.QRect(0, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_1.setFont(font)
        self.button_num_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_1.setObjectName("button_num_1")
        self.button_num_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_2.setGeometry(QtCore.QRect(100, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_2.setFont(font)
        self.button_num_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_2.setObjectName("button_num_2")
        self.button_num_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_3.setGeometry(QtCore.QRect(200, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_3.setFont(font)
        self.button_num_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_3.setObjectName("button_num_3")
        self.button_num_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_4.setGeometry(QtCore.QRect(0, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_4.setFont(font)
        self.button_num_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_4.setObjectName("button_num_4")
        self.button_num_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_5.setGeometry(QtCore.QRect(100, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_5.setFont(font)
        self.button_num_5.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_5.setObjectName("button_num_5")
        self.button_num_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_6.setGeometry(QtCore.QRect(200, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_6.setFont(font)
        self.button_num_6.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_6.setObjectName("button_num_6")
        self.button_num_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_7.setGeometry(QtCore.QRect(0, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_7.setFont(font)
        self.button_num_7.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_7.setObjectName("button_num_7")
        self.button_num_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_8.setGeometry(QtCore.QRect(100, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_8.setFont(font)
        self.button_num_8.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_8.setObjectName("button_num_8")
        self.button_num_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_9.setGeometry(QtCore.QRect(200, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_9.setFont(font)
        self.button_num_9.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_9.setObjectName("button_num_9")
        self.button_num_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_num_0.setGeometry(QtCore.QRect(0, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_num_0.setFont(font)
        self.button_num_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_num_0.setObjectName("button_num_0")
        self.button_result = QtWidgets.QPushButton(self.centralwidget)
        self.button_result.setGeometry(QtCore.QRect(200, 400, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_result.setFont(font)
        self.button_result.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"border-color: rgb(85, 255, 255);")
        self.button_result.setObjectName("button_result")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(300, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_plus.setFont(font)
        self.button_plus.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_plus.setObjectName("button_plus")
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setGeometry(QtCore.QRect(400, 100, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_minus.setFont(font)
        self.button_minus.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_minus.setObjectName("button_minus")
        self.button_multi = QtWidgets.QPushButton(self.centralwidget)
        self.button_multi.setGeometry(QtCore.QRect(300, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_multi.setFont(font)
        self.button_multi.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_multi.setObjectName("button_multi")
        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setGeometry(QtCore.QRect(400, 200, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_div.setFont(font)
        self.button_div.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_div.setObjectName("button_div")
        self.button_reset_string = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset_string.setGeometry(QtCore.QRect(300, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_reset_string.setFont(font)
        self.button_reset_string.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_reset_string.setObjectName("button_reset_string")
        self.button_reset_all = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset_all.setGeometry(QtCore.QRect(400, 300, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_reset_all.setFont(font)
        self.button_reset_all.setStyleSheet("background-color: rgb(255, 249, 67);\n"
"border-color: rgb(85, 255, 255);")
        self.button_reset_all.setObjectName("button_reset_all")
        self.button_point = QtWidgets.QPushButton(self.centralwidget)
        self.button_point.setGeometry(QtCore.QRect(100, 400, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.button_point.setFont(font)
        self.button_point.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(85, 255, 255);")
        self.button_point.setObjectName("button_point")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.button_num_1.setText(_translate("MainWindow", "1"))
        self.button_num_2.setText(_translate("MainWindow", "2"))
        self.button_num_3.setText(_translate("MainWindow", "3"))
        self.button_num_4.setText(_translate("MainWindow", "4"))
        self.button_num_5.setText(_translate("MainWindow", "5"))
        self.button_num_6.setText(_translate("MainWindow", "6"))
        self.button_num_7.setText(_translate("MainWindow", "7"))
        self.button_num_8.setText(_translate("MainWindow", "8"))
        self.button_num_9.setText(_translate("MainWindow", "9"))
        self.button_num_0.setText(_translate("MainWindow", "0"))
        self.button_result.setText(_translate("MainWindow", "="))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_multi.setText(_translate("MainWindow", "*"))
        self.button_div.setText(_translate("MainWindow", "/"))
        self.button_reset_string.setText(_translate("MainWindow", "CE"))
        self.button_reset_all.setText(_translate("MainWindow", "C"))
        self.button_point.setText(_translate("MainWindow", "."))

    def add_functions(self):
        self.button_num_0.clicked.connect(lambda: self.write_number(self.button_num_0.text()))
        self.button_num_1.clicked.connect(lambda: self.write_number(self.button_num_1.text()))
        self.button_num_2.clicked.connect(lambda: self.write_number(self.button_num_2.text()))
        self.button_num_3.clicked.connect(lambda: self.write_number(self.button_num_3.text()))
        self.button_num_4.clicked.connect(lambda: self.write_number(self.button_num_4.text()))
        self.button_num_5.clicked.connect(lambda: self.write_number(self.button_num_5.text()))
        self.button_num_6.clicked.connect(lambda: self.write_number(self.button_num_6.text()))
        self.button_num_7.clicked.connect(lambda: self.write_number(self.button_num_7.text()))
        self.button_num_8.clicked.connect(lambda: self.write_number(self.button_num_8.text()))
        self.button_num_9.clicked.connect(lambda: self.write_number(self.button_num_9.text()))

        self.button_plus.clicked.connect(lambda: self.write_number(self.button_plus.text()))
        self.button_minus.clicked.connect(lambda: self.write_number(self.button_minus.text()))
        self.button_multi.clicked.connect(lambda: self.write_number(self.button_multi.text()))
        self.button_div.clicked.connect(lambda: self.write_number(self.button_div.text()))

        self.button_point.clicked.connect(lambda: self.add_point())

        self.button_reset_string.clicked.connect(lambda: self.erase_symbol())
        self.button_reset_all.clicked.connect(lambda: self.reset())

        self.button_result.clicked.connect(self.get_result)

    def add_point(self):
        delimiters = "\\" + "|\\".join(self.math_operations)
        if '.' not in re.split(delimiters, self.label_result.text())[-1]:
            if self.label_result.text()[-1] in self.math_operations or self.label_result.text()[-1] == '.':
                self.label_result.setText(self.label_result.text()[:-1] + '.')
            else:
                self.label_result.setText(self.label_result.text() + '.')

    def write_number(self, number):
        if self.label_result.text() == '0':
            self.label_result.setText(number)
        else:
            if self.label_result.text()[-1] in self.math_operations and number in self.math_operations:
                self.label_result.setText(self.label_result.text()[:-1] + number)
            else:
                if self.label_result.text()[-1] == '.' and number in self.math_operations:
                    self.label_result.setText(self.label_result.text()[:-1] + number)
                else:
                    if self.label_result.text()[-1] == '0'and number not in self.math_operations:
                        self.label_result.setText(self.label_result.text() + '.' + number)
                    else:
                        self.label_result.setText(self.label_result.text() + number)

    def erase_symbol(self):
        if len(self.label_result.text()) > 1:
            self.label_result.setText((self.label_result.text()[:-1]))
        else:
            self.label_result.setText('0')

    def reset(self):
        self.label_result.setText('0')

    def get_result(self):
        try:
            if self.label_result.text()[-1] in self.math_operations:
                if len(self.label_result.text()) > 1:
                    self.label_result.setText(str(eval(self.label_result.text()[:-1])))
                else:
                    self.label_result.setText('0')
            else:
                self.label_result.setText(str(eval(self.label_result.text())))
        except ZeroDivisionError:
            error = QMessageBox()
            error.setWindowTitle('Деление на ноль')
            error.setText('На ноль делить нельзя, долбоёб!')
            error.setDetailedText('Ну, может быть, только в тривиальном кольце {0}. !0\\0=0 ????')
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Ok)
            error.exec_()
            self.reset()
